services:
  # Home Assistant service
  home-assistant:
    image: ghcr.io/home-assistant/home-assistant:latest
    container_name: home-assistant
    restart: unless-stopped
    privileged: true
    environment:
      - TZ=Europe/Brussels
    volumes:
      - ./config:/config
      - /run/dbus:/run/dbus:ro
    ports:
      - "8123:8123"
    networks:
      - home-network
    depends_on:
      - scanner

  scanner:
    build:
      context: ..
      dockerfile: client/Dockerfile
    container_name: client
    restart: unless-stopped
    environment:
      - TZ=Europe/Brussels
    volumes:
      - ..:/app
    devices:
      - /dev/video0:/dev/video0
    networks:
      - home-network
    ports:
      - "5000:5000"

  # host the camera stuff on this port. so we could have a home assistant on a differnet device and still have it work
   go2rtc:
    image: alexxit/go2rtc
    devices:
      - /dev/video0:/dev/video0
    ports:
      - "8554:8554"

networks:
  home-network:
    driver: bridge
