services:
  homeassistant:
    image: ghcr.io/home-assistant/home-assistant:stable
    container_name: homeassistant
    restart: unless-stopped
    network_mode: host
    cap_add:
      - NET_ADMIN
      - NET_RAW
    volumes:
      - ha_config:/config
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ=Europe/Brussels

  badge-scanner:
    build: .
    container_name: badge-scanner
    restart: unless-stopped
    network_mode: host
    environment:
      - RABBITMQ_HOST=localhost
      - RABBITMQ_USER=${RABBITMQ_USER}
      - RABBITMQ_PASS=${RABBITMQ_PASS}
      - RABBITMQ_PORT=5672
      - HOME_ASSISTANT_HOST=localhost
      - HOME_ASSISTANT_PORT=8123
      - HOME_ASSISTANT_TOKEN=${HOME_ASSISTANT_TOKEN}
      - TZ=Europe/Brussels
    depends_on:
      - homeassistant
    stdin_open: true
    tty: true

volumes:
  ha_config:
